version: '3'

services:
    server:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./deploymentconf:/etc/nginx/conf.d/
        environment: 
            - NGINX_PORT=80
        command: /bin/bash -c "exec nginx -g 'daemon off;'"
        depends_on: 
            - web
    db:
        image: postgres
    web:
        build: .
        image: &app app
        env_file: &envfile
            - docker.env
        command: ./gamemuster/start.sh
        volumes: 
            - .:/code
        depends_on:
            - db
            - broker
    worker:
        build: .
        image: *app
        env_file: *envfile
        command: ./gamemuster/celery.sh
        volumes:
            - .:/code
        depends_on:
            - db
            - broker
    broker:
        image: rabbitmq:3
        env_file: *envfile
        ports:
            - "5675:5672"